### ISSUE TITLE
Groups/qa/backend testing and quick debug/fixing

### ISSUE THREAD

**Issue by bshelor** [corpus-christi/corpus-christi#222]
## API
- [x] Run all group tests for `groups/test_groups.py`
- [x] Run all database tests possible
- [x] Take notes if something doesn't work/pass
- [x] Try to fix what you can.  Do not currently spend a considerable amount of time debugging it.

**Comment by jordaniwoodtaylor** [comment]
6 failing tests in test_groups.py. I will try to fix these, but anything that takes a lot of time or effort to fix I will leave for a future story.

**Comment by jordaniwoodtaylor** [comment]
**Remaining Test Failures:**
_test_delete_group_image_ AND 
_test_add_group_images_ AND 
_test_add_group_images_no_exist_ AND
_test_add_group_images_already_exist_: 
- line `create_multiple_groups(` is getting an error several functions deep. In test_people.py, manager_object_factory, the `random.choice(all_persons).id` _"Cannot choose from an empty sequence"_
- This may be a problem that can be more easily identified when coming at it from the people portion of the code, rather than groups. I am not sure exactly, but perhaps run the people tests as well.

_test_read_all_groups_:
- This test creates multiple groups, but then when getting those groups, it only finds one. I think this is a real bug that the unit test is finding, not a badly written test. I don't know if the problem is when creating, or accessing the groups though. 

_test_create_group_:
- I don't know what this problem is, but it may be the same root problem as the read_all_groups test. Error is in the function call `group_object_factory_with_members(auth_client.sqla)`
