### ISSUE TITLE
Groups - Add group button - Add manager to group

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#439]
In groups when adding a new group.  When a manager is appointed, and the group is created, the manager should be added as an active member of the group (if they are archived, unarchive them and set them as the manager)

- [ ] When a new group is added.  Add the selected manager into the member's table.
- [ ] Manually test this checking that when adding a new group (with no members) that the manager shows up as the only person in the group.
- [ ] If a manager is changed (in the edit mode), make sure that the new manager is added as part of the group and added to the group table.  Note that we still want to keep the old manager as a member if a new manager is appointed.

**Comment by PROgram52bc** [comment]
Under the current model where one group can have multiple managers, managers act very similar to members, except they have an additional `manager_type` attribute. So it seems a little unnecessary to duplicate every manager to the member table, rather than providing the flexibility for a person to be a manager or a member of a group, or both.
