### ISSUE TITLE
HomeGroup -> Generic Church Group Transition: Refactor Groups

### ISSUE THREAD

**Issue by mattddean** [corpus-christi/corpus-christi#494]
Massive changes were made to the ERD in relation to the way Groups work. Groups can now represent more than HomeGroups. In particular, the Manager table has gone away, having been replaced by ~a Management~ the new Manager table, and groups can now have multiple managers through that table.

**Comment by PROgram52bc** [comment]
To resolve this issue, the following subtasks are identified.
- Database:
  - [x] Add Group-Type table
  - [x] Add Manager-Type table
  - [x] Other modifications to match ERD
- API:
  - [x] Implement CRUD pattern for Group-Type
  - [x] Implement CRUD pattern for Manager-Type
  - [x] CRUD for `Group`, now with a foreign key `group_type_id`
  - [x] CRUD for `Manager`, should be nested routes in the form of `group/<group_id>/managers/<person_id>`, also handle a payload including the foreign keys such as `person_id`
  - [x] CRUD for `Member`, should be nested routes in the form of `group/<group_id>/members/<person_id>`, also handle a payload including the foreign keys such as `person_id`
  - [x] implement query string parsing on `get_all*` endpoints

- Testing:
  - [x] Implement test for Group-Type
  - [x] Implement test for Manager-Type
  - [x] Implement test for Group
  - [x] Implement test for Manager
  - [x] Implement test for Member
  - [x] Add test for query strings on `get_all*` endpoints
  - [ ] solidify and move `get_all*` query string tests to a designated place

- User Interface:
  - [ ] When creating a group, show a selection (with the ability to add and remove) of `group_type`s, remove the search for manager option.
  - [ ] In the page for a specific `Group`, display the list of managers (instead of just one manager) for a group, and their management types.

- ETC:
  - [x] Clean up the `create_group_data` file

**Comment by quiteqiang** [comment]
UI:
 - [ ] Add attendence to the Meeting page

**Comment by PROgram52bc** [comment]
Database and API done #525 , UI moved to #542
