### ISSUE TITLE
Error handling and reporting

### ISSUE THREAD

**Issue by quiteqiang** [corpus-christi/corpus-christi#530]
Require more user-friendly report in Group module

**Comment by PROgram52bc** [comment]
To resolve this issue, we need to consider at least the following aspects:

- [x] standard way of displaying error in the UI (e.g. a snackbar component)
- [x] integrate the error catching logic into axios
- [x] logging technical errors through a standard logging mechanism to the console (see #527 and https://flask.palletsprojects.com/en/1.1.x/logging/)
- [ ] changing api error response message to a more user-friendly string (e.g. "user <name> does not exist" instead of "user with \<id\> does not exist)
  - [ ] extract from `IntegrityError` object useful information to display
  - [ ] investigate ways to make marshmallow validation errors more user-friendly.
- [ ] internationalize the api error response message (https://docs.python.org/3/library/gettext.html or https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting)
- [x] implement a feedback mechanism
  - [x] a separate UI component to report error
  - [x] an endpoint to accept error
  - [x] a database table to store the error reported by users
    Should accept a payload from end user containing: 
    - a timestamp of when the error was intercepted,
    - a description from the user about how the error occured, 
    - the http response error code,
    - the url of the request that failed,
    - the error message responded by the server upon error

**Comment by PROgram52bc** [comment]
Mostly resolved in #536 and #539 , additional features (such as a way for UI to override the default error message with a specific one) should be addressed in a new issue.
