### ISSUE TITLE
Circular  Hierarchy

### ISSUE THREAD

**Issue by quiteqiang** [corpus-christi/corpus-christi#583]
The relationship between multiple groups could be a circle that might cause problems. 

Current solutions is to use an algorithm(Breadth-First Search) to search if a manager appeared more than once in a tree.

**Comment by PROgram52bc** [comment]
The following needs to be taken care of

- [x] in `create_group_data`, the members and managers generated should not create cycle in the leadership hierarchy.
- [x] check when adding a manager/member, whether it would create cycle
- [x] check in member/manager movement, whether it will create cycle
- [x] check in reactivating member/manager, whether it will create cycle
- [x] check in reactivating a group, whether it will create cycle
---
- [x] retrieve a list of person in groupMixin in order to draw admin tree
- [x] fix `adminTree`: 
   - [x] using a combination of persons and groups for rootNode filtering
   - [x] use the `map` function instead of `parse(stringify())` idiom
- [x] remove `toJSON` function from `GraphNode`
- [x] possibly get rid of the `transform` option in `dfs`, replace all usage with `map`

**Comment by PROgram52bc** [comment]
Roadmap
- create typescript classes
   - define `Member`, `Manager`, `Group` classes, as subclasses of class `HierarchyNode`. Constructor(MemberObject | ManagerObject | GroupObject, groupMap: GroupMap).
   - define methods on `HierarchyNode`: `getSubNodes()`, and `getSuperNodes()`
   - define methods on Member and Manager: `getLeadingGroups()`, `getParticipatingGroups()`
   - define methods on Group: `getManagers()`, `getMembers()`
   - define method `nodeType` that returns a string, being either `Group`, `Member`, or `Manager`
   - define algorithms to check whether a linkage between two `HierarchyNode`s will cause cycle.
   - define algorithms to return all `subGroups` or all `superGroups` of a given `HierarchyNode`.

- ~~create vue mixin wrapper~~
  - ~~takes a string as [parameter](https://www.reactjunkie.com/vue-mixin-args), indicating the component property name where a list of groups can be found (default to `groups`).~~

  - ~~internally keep a computed property `_groupmap` that transforms the passed in groups list~~
- generate hard-coded manager/member list in json form that does not violate the circular-hierarchy constraint
- write documentation with diagram illustrating
  - the constraint
  - the concept of supervisor that extends permission of group manager

**Comment by PROgram52bc** [comment]
Fix:
- [x] `saveLocalParticipants` does not update `cyclingPersons` upon archiving person 1 in the default dataset. The result is person 1 cannot be reactivated immediately after being archived. Not sure if the issue comes from the vue reactivity system or the HierarchyNode algorithms. To debug the algorithms, make `checkConnection` return a path, by retaining the graph of `dfs` and construct the cycling path

Consider:
- ~~Should we allow a person to be manager/member of multiple groups? Then we can have a graph like: G3 -> P1 -> G1 -> P1 -> G3... Although it should terminate at the second P1.~~ Yes.

**Comment by PROgram52bc** [comment]
Wrap up:

- [x] add internationalization to GroupTreeViewHierarchy page
- [x] implement check for cycle upon reactivating a group
- [x] modify existing `checkConnection` implementation, to include a path that creates the cycle, and allow cases like G2 -> P1 -> G2 -> P3 -> G2 to pass. Basically ignore (not add to collection, not search further) nodes whose grandparent node is identical to itself.
- [x] write documentation
   - [x] explain the concept of leadership hierarchy, introduce key terms (super nodes, sub nodes, parent nodes, grandparent nodes. ...), perhaps rename the functions from `getSuperNodes` to `getParentNodes` to improve consistency.
   - [x] explain how one's permissions is determined based on the leadership hierarchy
   - [x] explain the concept of rootNode, and how an `adminTree` is drawn.
   - [x] cases where hierarchy structure is valid, and show admin graph drawn
   - [x] cases where hierarchy structure is invalid, and explain why
   - [x] add link to the stories.md file
