### ISSUE TITLE
Verified count doesn't change in toolbox.

### ISSUE THREAD

**Issue by nurkkala** [corpus-christi/corpus-christi#710]
After checking a "verified" box, the count of verified translations shown in the toolbox does not change.

**Comment by josephvanderharst** [comment]
The 'verified count' is set to reflect the number of verified translations from the _database's_ point of view.
In [this commit](https://github.com/corpus-christi/corpus-christi/commit/5a38ebfe273c2e5875ea76cdfa64d2966d3bba9a), it has been changed so that the checkbox is a clearly different (non-error) color until the user submits his/her change, in which case the color matches the text-color of the verification count.
